name: "CI"

on:
  push:
    branches-ignore:
      - main
      - restyled/*

jobs:
  pre-release:
    name: "Pre Release latest"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - name: install platform io
        run: | 
          pip3 install -U setuptools
          pip3 install -U wheel
          pip3 install -U platformio
          python3 -m platformio update
          
      - name: run unit tests
        run: python3 -m platformio test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-artifact
          path: .